/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jecfbagsx_android_video_FrameCapture */

#ifndef _Included_com_jecfbagsx_android_video_FrameCapture
#define _Included_com_jecfbagsx_android_video_FrameCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    openFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jecfbagsx_android_video_FrameCapture_openFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    getNextFrame
 * Signature: (IIIILandroid/graphics/Bitmap;)J
 */
JNIEXPORT jlong JNICALL Java_com_jecfbagsx_android_video_FrameCapture_getNextFrame
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    seekTo
 * Signature: (IIIJLandroid/graphics/Bitmap;)J
 */
JNIEXPORT jlong JNICALL Java_com_jecfbagsx_android_video_FrameCapture_seekTo
  (JNIEnv *, jobject, jint, jint, jint, jlong, jobject);

/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    getFileDuration
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_jecfbagsx_android_video_FrameCapture_getFileDuration
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    getFileResolutionWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jecfbagsx_android_video_FrameCapture_getFileResolutionWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    getFileResolutionHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jecfbagsx_android_video_FrameCapture_getFileResolutionHeight
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jecfbagsx_android_video_FrameCapture_release
  (JNIEnv *, jobject);

/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    native_setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jecfbagsx_android_video_FrameCapture_native_1setup
  (JNIEnv *, jobject);

/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jecfbagsx_android_video_FrameCapture_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    native_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jecfbagsx_android_video_FrameCapture_native_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_jecfbagsx_android_video_FrameCapture
 * Method:    scaleImage
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)J
 */
JNIEXPORT jlong JNICALL Java_com_jecfbagsx_android_video_FrameCapture_scaleImage
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
